[workspace]
members = ["frontend", "backend", "shared"]
resolver = "3"

[workspace.package]
version = "1.0.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
anyhow = "1.0.99"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
fullstack-model = { path = "shared" }

[profile.release]
lto = true
opt-level = "s"
codegen-units = 1
strip = "debuginfo"
