[package]
name = "az-aio-codegen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "AIO client-side Rust enum and struct generator."

[dependencies]
anyhow.workspace = true
axum.workspace = true
az-aio-platform = { path = "../../platform" }
az-str.workspace = true
dioxus.workspace = true
prettyplease.workspace = true
rudi.workspace = true
registry.workspace = true
serde.workspace = true
serde_json.workspace = true
syn.workspace = true
tokio.workspace = true
urlencoding.workspace = true

[dev-dependencies]
tempfile = "3.23.0"
tower.workspace = true

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
