[package]
name = "az-ssh"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
automod.workspace = true
derive_more.workspace = true
ssh2.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
