[workspace]

[package]
name = "az-plugin-industrial-protocol-gateway"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT OR Apache-2.0"
authors = ["zjarlin"]
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
az-derive-aliases = { path = "../../../../../crates/core/az-derive-aliases" }
derive_more = { version = "2.1.1", features = ["display"] }
thiserror = "2.0.17"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
