// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!

@file:OptIn(kotlin.wasm.unsafe.UnsafeWasmMemoryApi::class, kotlin.wasm.ExperimentalWasmInterop::class, kotlin.wasm.unsafe.ComponentModelInternalApi::class)
@file:Suppress("REDUNDANT_ELSE_IN_WHEN")

package __PACKAGE_NAME__.bindings
import __PACKAGE_NAME__.component.PageRootFunctionsExportsImpl

import __PACKAGE_NAME__.bindings.runtime.*
import kotlin.wasm.unsafe.componentModelRealloc


@kotlin.wasm.WasmExport("definition")
fun __wasm_export_definition(): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val result: kotlin.String = PageRootFunctionsExportsImpl.definition()

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(2*4), align=4)*/ allocator.allocate((2*4)).address.toInt()

  val bytearray = result.encodeToByteArray()
  val len = bytearray.size
  val ptr0 = allocator.writeToLinearMemory(bytearray).address.toInt()

  (ptr + 4).ptr.storeInt(len)
  (ptr + 0).ptr.storeInt(ptr0)
  return ptr
}
}

/* UNUSED
@kotlin.wasm.WasmExport("cabi_post_definition")
fun cabi_post___wasm_export_definition(p0: kotlin.Int) {
  // GuestDeallocateString(len=(p0 + 4).ptr.loadInt(), ptr=(p0 + 0).ptr.loadInt())

}
*/

@kotlin.wasm.WasmExport("handle")
fun __wasm_export_handle(p0: kotlin.Int, p1: kotlin.Int): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val result: kotlin.String = PageRootFunctionsExportsImpl.handle(__PACKAGE_NAME__.bindings.runtime.STRING_FROM_MEM(p0, p1))

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(2*4), align=4)*/ allocator.allocate((2*4)).address.toInt()

  val bytearray = result.encodeToByteArray()
  val len = bytearray.size
  val ptr0 = allocator.writeToLinearMemory(bytearray).address.toInt()

  (ptr + 4).ptr.storeInt(len)
  (ptr + 0).ptr.storeInt(ptr0)
  return ptr
}
}

/* UNUSED
@kotlin.wasm.WasmExport("cabi_post_handle")
fun cabi_post___wasm_export_handle(p0: kotlin.Int) {
  // GuestDeallocateString(len=(p0 + 4).ptr.loadInt(), ptr=(p0 + 0).ptr.loadInt())

}
*/
