[package]
name = "algorithm-center"
description = "algorithm center native plugin — browse and introspect az-algorithm components."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
automod.workspace = true
axum.workspace = true
az-aio-platform = { path = "../../platform" }
az-aio-nature-generated.workspace = true
az-algorithm.workspace = true
az-str.workspace = true
md5.workspace = true
rudi.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
urlencoding.workspace = true

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
dbg_macro = "deny"
todo = "deny"

[dev-dependencies]
tower = "0.5.2"
