[package]
name = "az-aio-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Create AIO application shells and multilingual Git plugins."
repository.workspace = true
workspace = ".."

[[bin]]
name = "aio"
path = "src/main.rs"

[dependencies]
include_dir = "0.7.4"
anyhow.workspace = true
az-plugin-manifest = { workspace = true, features = ["schema", "validation"] }
az-plugin-package.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
toml_edit.workspace = true

[dev-dependencies]
tempfile = "3.23.0"

[lints]
workspace = true
