export {
  capabilityAuditLogApi,
  capabilityBrowserOpenUrlApi,
  capabilityClipboardReadApi,
  capabilityClipboardWriteApi,
  capabilityFsReadApi,
  capabilityFsWriteApi,
  capabilityInvokeApi,
  capabilityNotificationSendApi,
  capabilityProcessExecApi,
  permissionApprovalApproveApi,
  permissionApprovalDenyApi,
  permissionApprovalListApi,
  permissionAuditLogApi,
  permissionConsentGrantApi,
  permissionConsentListApi,
  permissionConsentRevokeApi,
} from '../local/system';
