const assert=require('node:assert/strict');
const fs=require('node:fs');
const {resolve}=require('node:path');
const {createHash}=require('node:crypto');
const {gunzipSync}=require('node:zlib');
const {execFileSync,spawnSync}=require('node:child_process');
assert.equal(process.getuid(),0,'Installation requires root');
const [archive,input]=process.argv.slice(2);
assert(archive&&input,'Usage: node install.cjs <release.gz> <private-config.json>');
const bytes=fs.readFileSync(archive);
assert.equal(createHash('sha256').update(bytes).digest('hex'),'3393345527c6628f47c295e2f1dfd182454800f964f3211f606d3aab0fdfc5a9');
const config=JSON.parse(fs.readFileSync(input,'utf8'));
assert(Array.isArray(config.proxies)&&config.proxies.length>0);
const gateway=execFileSync('docker',['network','inspect','bridge','--format','{{range .IPAM.Config}}{{.Gateway}}{{end}}'],{encoding:'utf8'}).trim();
assert.equal(gateway,'172.17.0.1','Review the listener configuration for a different Docker subnet');
Object.assign(config,{'mixed-port':17892,'bind-address':gateway,'allow-lan':true,'lan-allowed-ips':['172.17.0.0/16'],'external-controller':'','geo-auto-update':false,tun:{enable:false}});
if(spawnSync('id',['aio-egress'],{stdio:'ignore'}).status!==0)execFileSync('useradd',['--system','--home-dir','/nonexistent','--shell','/sbin/nologin','aio-egress']);
const uid=Number(execFileSync('id',['-u','aio-egress'],{encoding:'utf8'}));
const gid=Number(execFileSync('id',['-g','aio-egress'],{encoding:'utf8'}));
const root='/opt/aio-delivery/egress';
fs.mkdirSync(root,{recursive:true,mode:0o750});
fs.chmodSync(root,0o750);
fs.chownSync(root,0,gid);
fs.mkdirSync(`${root}/state`,{recursive:true,mode:0o750});
fs.chownSync(`${root}/state`,uid,gid);
fs.writeFileSync(`${root}/proxy`,gunzipSync(bytes),{mode:0o755});
fs.writeFileSync(`${root}/config.json`,JSON.stringify(config),{mode:0o640});
fs.chmodSync(`${root}/config.json`,0o640);
fs.chownSync(`${root}/config.json`,0,gid);
execFileSync(`${root}/proxy`,['-t','-d',`${root}/state`,'-f',`${root}/config.json`],{stdio:'ignore'});
fs.copyFileSync(resolve(__dirname,'service'),'/etc/systemd/system/aio-egress.service');
fs.mkdirSync('/etc/systemd/system/aio-delivery.service.d',{recursive:true});
fs.writeFileSync('/etc/systemd/system/aio-delivery.service.d/egress.conf','[Unit]\nAfter=aio-egress.service\nWants=aio-egress.service\n');
execFileSync('systemctl',['daemon-reload']);
execFileSync('systemctl',['enable','aio-egress'],{stdio:'ignore'});
execFileSync('systemctl',['restart','aio-egress']);
console.log(JSON.stringify({service:'aio-egress',listener:`http://${gateway}:17892`,routes:config.proxies.length}));
