[package]
name = "az-aio-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "AIO single-package full-stack Dioxus application."
workspace = ".."

[target.'cfg(target_arch = "wasm32")'.dependencies]
az-ui-components.workspace = true
dioxus = { workspace = true, features = ["web", "launch"] }
studio = { package = "az-studio", path = "plugins/studio", default-features = false, features = ["web"] }
web-sys = { version = "0.3.82", features = ["Location", "Window"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
anyhow.workspace = true
automod.workspace = true
axum.workspace = true
az-plugin-core.workspace = true
business = { package = "az-biz-aio-first-party", path = "../lib/biz/aio-first-party" }
dill.workspace = true
dotenvy.workspace = true
sqlx.workspace = true
studio = { package = "az-studio", path = "plugins/studio", default-features = false, features = ["server"] }
tokio.workspace = true
tower-http.workspace = true

[lints]
workspace = true
