[package]
name = "az-edge-gateway"
description = "edge gateway native plugin."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
az-plugin-core = { path = "../../../crates/plugin/core" }
automod.workspace = true
az-str.workspace = true
handlebars.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
serde_json_path.workspace = true
rudi.workspace = true
tokio.workspace = true
toasty.workspace = true
urlencoding.workspace = true

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
dbg_macro = "deny"
todo = "deny"

[dev-dependencies]
tower.workspace = true
