[package]
name = "az-asset-hub"
description = "asset hub native plugin."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
az-asset-hub-contract.workspace = true
az-plugin-core = { path = "../../../crates/plugin/core" }
az-str.workspace = true
automod.workspace = true
rudi.workspace = true
serde.workspace = true
tokio.workspace = true
toasty.workspace = true

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
