[package]
name = "aio-front"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
description = "AIO admin front prototype built with adui-dioxus."

[dependencies]
adui-dioxus = { path = "../../../vendor/adui-dioxus" }
dioxus.workspace = true
dioxus-ssr.workspace = true
serde_json.workspace = true

[lints]
workspace = true
