#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct DotfileSpace {
    pub slug: &'static str,
    pub title: &'static str,
    pub target_root_path: &'static str,
    pub description: &'static str,
    pub cloud_rule: &'static str,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct DotfileEntry {
    pub slug: &'static str,
    pub space_slug: &'static str,
    pub logical_key: &'static str,
    pub label: &'static str,
    pub target_path: &'static str,
    pub kind: &'static str,
    pub platform: &'static str,
    pub status: &'static str,
    pub sync_mode: &'static str,
    pub target_reason: &'static str,
    pub conflict_hint: &'static str,
    pub note: &'static str,
}

pub const DOTFILE_SPACES: &[DotfileSpace] = &[
    DotfileSpace {
        slug: "home-dotfiles",
        title: "Home 顶层 dotfiles",
        target_root_path: "~",
        description: "PG 里记录用户级入口配置，agent 如需同步，就把期望态下发到 home 根目录。",
        cloud_rule: "云端先维护逻辑键和期望内容，home 根目录只是其中一个目标落点。",
    },
    DotfileSpace {
        slug: "xdg-config",
        title: "XDG / ~/.config",
        target_root_path: "~/.config",
        description: "CLI、编辑器和 shell 片段优先纳入 XDG 根目录，表结构按 logical key + file metadata 管理。",
        cloud_rule: "云端按逻辑键、定义类型、平台范围和目标路径建档，不把本机文件扫描结果当正式主数据。",
    },
    DotfileSpace {
        slug: "macos-library",
        title: "macOS Library",
        target_root_path: "~/Library",
        description: "macOS 原生 GUI 配置继续按系统目录落地，PG 统一管理这些目标路径与同步策略。",
        cloud_rule: "不把 GUI 配置强制搬到 ~/.config；数据库记期望态，agent 视能力决定是否同步。",
    },
    DotfileSpace {
        slug: "system",
        title: "系统级配置",
        target_root_path: "/etc",
        description: "系统级目标路径单独建档，PG 统一管理，agent 未来通过提权同步和审计流程处理。",
        cloud_rule: "数据库管理规则和期望态，真正写入 /etc 时必须经过提权、预览和冲突确认。",
    },
];

pub const DOTFILE_ENTRIES: &[DotfileEntry] = &[
    DotfileEntry {
        slug: "zshrc",
        space_slug: "home-dotfiles",
        logical_key: "shell.zshrc",
        label: ".zshrc",
        target_path: "~/.zshrc",
        kind: "Shell Entry",
        platform: "macOS",
        status: "已登记",
        sync_mode: "可选同步",
        target_reason: "登录 shell 的入口文件仍然应该落在 home 根目录，但它的期望态由 PG 保存。",
        conflict_hint: "冲突时优先人工确认，避免覆盖用户临时 source 或本机热修。",
        note: "常用于 source ~/.config/shell/* 或加载环境变量入口。",
    },
    DotfileEntry {
        slug: "gitconfig",
        space_slug: "home-dotfiles",
        logical_key: "git.user_config",
        label: ".gitconfig",
        target_path: "~/.gitconfig",
        kind: "Identity",
        platform: "Cross-platform",
        status: "已登记",
        sync_mode: "可选同步",
        target_reason: "Git 默认读取 home 下用户配置，agent 同步时只需要把 PG 期望态下发到该路径。",
        conflict_hint: "适合做结构化 diff，优先保留 include 拆分并提示人工合并身份信息。",
        note: "全局用户名、签名和 includeIf 拆分策略的总入口。",
    },
    DotfileEntry {
        slug: "ssh-config",
        space_slug: "home-dotfiles",
        logical_key: "ssh.user_config",
        label: ".ssh/config",
        target_path: "~/.ssh/config",
        kind: "Credential",
        platform: "macOS/Linux",
        status: "已登记",
        sync_mode: "保守同步",
        target_reason: "SSH 客户端约定路径明确，数据库只记录配置文本和策略，不托管私钥本体。",
        conflict_hint: "遇到冲突默认跳过并提示人工确认，避免误伤跳板和临时主机别名。",
        note: "后续同步时需要把密钥文件与纯文本配置分开处理。",
    },
    DotfileEntry {
        slug: "config-git",
        space_slug: "xdg-config",
        logical_key: "git.xdg_root",
        label: "git/",
        target_path: "~/.config/git/",
        kind: "CLI Config",
        platform: "Cross-platform",
        status: "已登记",
        sync_mode: "目录同步",
        target_reason: "Git 模块化配置适合按目录落地，云端保留逻辑结构，agent 决定同步哪些片段。",
        conflict_hint: "目录级 diff 后按文件选择性 apply，避免整目录覆盖。",
        note: "和 ~/.gitconfig 配合使用，作为模块化子配置根。",
    },
    DotfileEntry {
        slug: "config-nvim",
        space_slug: "xdg-config",
        logical_key: "editor.nvim_root",
        label: "nvim/",
        target_path: "~/.config/nvim/",
        kind: "Editor Config",
        platform: "Cross-platform",
        status: "已登记",
        sync_mode: "目录同步",
        target_reason: "Neovim 天然使用 XDG 根目录，PG 保存编辑器期望态，agent 再把目录下发到本机。",
        conflict_hint: "推荐目录 diff + 手动挑选片段，避免本机实验配置被整包替换。",
        note: "适合作为插件、LSP、snippets 和键位的聚合根目录。",
    },
    DotfileEntry {
        slug: "config-ghostty",
        space_slug: "xdg-config",
        logical_key: "terminal.ghostty_root",
        label: "ghostty/",
        target_path: "~/.config/ghostty/",
        kind: "Terminal Config",
        platform: "macOS",
        status: "已登记",
        sync_mode: "目录同步",
        target_reason: "终端类应用若支持 ~/.config，就把目标路径登记在 PG，再由 agent 选择性同步。",
        conflict_hint: "建议以文件粒度预览差异，再决定是否覆盖本机主题和快捷键。",
        note: "主题、字体和快捷键可以继续拆成子文件。",
    },
    DotfileEntry {
        slug: "config-opencode",
        space_slug: "xdg-config",
        logical_key: "agent.opencode_root",
        label: "opencode/",
        target_path: "~/.config/opencode/",
        kind: "Agent Config",
        platform: "Cross-platform",
        status: "已登记",
        sync_mode: "目录同步",
        target_reason: "Agent 运行参数本身就是云端管理对象，PG 保存逻辑配置，再下发到各端目标目录。",
        conflict_hint: "适合让 agent 提供可选同步方案，冲突时做结构化 merge 或逐项确认。",
        note: "后续 Win/mac agent 同步时可以把这里作为 collect/apply 根。",
    },
    DotfileEntry {
        slug: "config-zed",
        space_slug: "xdg-config",
        logical_key: "editor.zed_root",
        label: "zed/",
        target_path: "~/.config/zed/",
        kind: "Editor Config",
        platform: "macOS/Linux",
        status: "已登记",
        sync_mode: "目录同步",
        target_reason: "支持 XDG 的图形编辑器适合由 PG 管理逻辑配置，再同步到 ~/.config/zed。",
        conflict_hint: "优先按文件 diff，保留本机实验性 keymap 的选择权。",
        note: "和 VS Code、Cursor 这类仍使用 Library 的应用保持清晰分界。",
    },
    DotfileEntry {
        slug: "config-shell-root",
        space_slug: "xdg-config",
        logical_key: "shell.root",
        label: "shell/",
        target_path: "~/.config/shell/",
        kind: "Shell Root",
        platform: "macOS/Linux",
        status: "已整理",
        sync_mode: "目录同步",
        target_reason: "shell 目录是 Bash/Zsh 公共片段的聚合根，适合按目录作为正式配置资产建档。",
        conflict_hint: "优先目录级 diff，但 profile/rc/local 片段不建议整包覆盖。",
        note: "结构参考 ~/.config/shell/README.md，也对齐 legacy xlsx 的 shell 元数据表意。",
    },
    DotfileEntry {
        slug: "shell-loader",
        space_slug: "xdg-config",
        logical_key: "shell.lib.loader",
        label: "lib/loader.sh",
        target_path: "~/.config/shell/lib/loader.sh",
        kind: "Shell Loader",
        platform: "macOS/Linux",
        status: "已整理",
        sync_mode: "文件同步",
        target_reason: "集中提供 source 目录和 PATH 管理能力，是 profile.d / rc.d 的基础依赖。",
        conflict_hint: "一旦改动会影响整个 shell 装载顺序，优先要求预览差异后再覆盖。",
        note: "对应 legacy xlsx 里的共用 shell helper，不需要在 Web 中展示任何 secret value。",
    },
    DotfileEntry {
        slug: "shell-profile-homebrew",
        space_slug: "xdg-config",
        logical_key: "shell.profile.homebrew",
        label: "profile.d/10-homebrew.sh",
        target_path: "~/.config/shell/profile.d/10-homebrew.sh",
        kind: "Shell Export",
        platform: "macOS",
        status: "已整理",
        sync_mode: "文件同步",
        target_reason: "负责 brew shellenv 和镜像源变量，属于登录 shell 环境初始化片段。",
        conflict_hint: "如果本机 Homebrew 前缀不同，不应盲目回写；优先做机器级差异确认。",
        note: "可以映射到 legacy xlsx 的 export 元数据列，但不单独拆出每个变量值。",
    },
    DotfileEntry {
        slug: "shell-profile-toolchains",
        space_slug: "xdg-config",
        logical_key: "shell.profile.toolchains",
        label: "profile.d/20-toolchains.sh",
        target_path: "~/.config/shell/profile.d/20-toolchains.sh",
        kind: "Shell Export",
        platform: "macOS",
        status: "已整理",
        sync_mode: "文件同步",
        target_reason: "统一 Java、Rust、pnpm、Gradle 等 toolchain 的家目录和 PATH 入口。",
        conflict_hint: "目录路径和版本依赖主机环境，推荐保留结构化字段并按机器渲染。",
        note: "对齐 xlsx 里的 export / PATH 规则，但 Web 侧只登记文件级元数据。",
    },
    DotfileEntry {
        slug: "shell-profile-user-env",
        space_slug: "xdg-config",
        logical_key: "shell.profile.user_env",
        label: "profile.d/30-user-env.sh",
        target_path: "~/.config/shell/profile.d/30-user-env.sh",
        kind: "Shell Export",
        platform: "Cross-platform",
        status: "已整理",
        sync_mode: "文件同步",
        target_reason: "放公共语言环境、时区、浏览器和 no_proxy 规则，适合作为可审计的登录环境层。",
        conflict_hint: "多个机器若网络域不同，应优先做变量级 merge，而不是整文件覆盖。",
        note: "相当于 legacy xlsx 里的 export 元数据集合，但值仍以文件为准。",
    },
    DotfileEntry {
        slug: "shell-profile-user-paths",
        space_slug: "xdg-config",
        logical_key: "shell.profile.user_paths",
        label: "profile.d/40-user-paths.sh",
        target_path: "~/.config/shell/profile.d/40-user-paths.sh",
        kind: "Shell Path",
        platform: "macOS",
        status: "已整理",
        sync_mode: "文件同步",
        target_reason: "管理用户级 PATH 追加和 rustup 更新源，属于路径策略层。",
        conflict_hint: "不同机器 Python / JetBrains 路径可能不同，建议保留局部 override 能力。",
        note: "适合未来入 PG 时拆成 path policy，而不是直接记录单个 alias。",
    },
    DotfileEntry {
        slug: "shell-profile-jetbrains",
        space_slug: "xdg-config",
        logical_key: "shell.profile.jetbrains",
        label: "profile.d/50-jetbrains.sh",
        target_path: "~/.config/shell/profile.d/50-jetbrains.sh",
        kind: "Shell Shim",
        platform: "macOS",
        status: "已整理",
        sync_mode: "文件同步",
        target_reason: "只负责桥接本地 JetBrains VM options 入口，保持 shell 主线干净。",
        conflict_hint: "如果本机没有对应文件，应该允许无损跳过而不是报错。",
        note: "属于轻量 include 片段，可以单独做存在性元数据。",
    },
    DotfileEntry {
        slug: "shell-profile-legacy-env",
        space_slug: "xdg-config",
        logical_key: "shell.profile.legacy_env",
        label: "profile.d/60-legacy-env.sh",
        target_path: "~/.config/shell/profile.d/60-legacy-env.sh",
        kind: "Shell Export",
        platform: "macOS",
        status: "兼容迁移",
        sync_mode: "文件同步",
        target_reason: "承接旧 shell 片段迁移过来的环境变量和 Java 版本兼容层。",
        conflict_hint: "这类变量历史包袱重，建议按条目拆分后再逐步入 PG，不要粗暴覆盖。",
        note: "保留 legacy 兼容语义，但已经适合按 xlsx 风格做元数据登记。",
    },
    DotfileEntry {
        slug: "shell-rc-aliases",
        space_slug: "xdg-config",
        logical_key: "shell.rc.aliases",
        label: "rc.d/10-aliases.sh",
        target_path: "~/.config/shell/rc.d/10-aliases.sh",
        kind: "Shell Alias",
        platform: "macOS/Linux",
        status: "已整理",
        sync_mode: "文件同步",
        target_reason: "公共 alias 集中在互动 shell 层，便于后续拆成 alias 元数据表。",
        conflict_hint: "alias 名冲突较常见，建议按 name 粒度展示 diff，而不是只看整文件。",
        note: "与 biz_dotfiles.xlsx 的 alias 行语义最接近，适合统一进表格。",
    },
    DotfileEntry {
        slug: "shell-rc-legacy-aliases",
        space_slug: "xdg-config",
        logical_key: "shell.rc.legacy_aliases",
        label: "rc.d/15-legacy-aliases.sh",
        target_path: "~/.config/shell/rc.d/15-legacy-aliases.sh",
        kind: "Shell Alias",
        platform: "macOS",
        status: "兼容迁移",
        sync_mode: "文件同步",
        target_reason: "承接旧版应用启动器和工具别名，先保持兼容，再逐步收敛。",
        conflict_hint: "存在历史工具路径和镜像地址，适合按 alias 级别逐条迁移。",
        note: "legacy xlsx 中的 alias 元数据可优先映射到这一层。",
    },
    DotfileEntry {
        slug: "shell-rc-functions",
        space_slug: "xdg-config",
        logical_key: "shell.rc.functions",
        label: "rc.d/20-functions.sh",
        target_path: "~/.config/shell/rc.d/20-functions.sh",
        kind: "Shell Function",
        platform: "macOS",
        status: "已整理",
        sync_mode: "文件同步",
        target_reason: "公共函数如 commonip、killport 属于交互逻辑，适合按函数集归档。",
        conflict_hint: "函数改动可能影响 CLI 工作流，建议支持函数级 diff 和预览。",
        note: "对齐 xlsx 的 function 元数据语义，但不在 Web 中回显实现细节全文。",
    },
    DotfileEntry {
        slug: "shell-rc-autohost",
        space_slug: "xdg-config",
        logical_key: "shell.rc.autohost",
        label: "rc.d/22-autohost.sh",
        target_path: "~/.config/shell/rc.d/22-autohost.sh",
        kind: "Shell Function",
        platform: "macOS/Linux",
        status: "已整理",
        sync_mode: "文件同步",
        target_reason: "autohost 负责本地端口与 tunnel 入口编排，属于 shell 自动化函数集的一部分。",
        conflict_hint: "和本机 Docker / tunnel 环境强相关，建议把端口策略与函数实现分层管理。",
        note: "是函数型元数据，不是普通导出变量，适合单独分类。",
    },
    DotfileEntry {
        slug: "shell-rc-legacy-functions",
        space_slug: "xdg-config",
        logical_key: "shell.rc.legacy_functions",
        label: "rc.d/25-legacy-functions.sh",
        target_path: "~/.config/shell/rc.d/25-legacy-functions.sh",
        kind: "Shell Function",
        platform: "macOS/Linux",
        status: "兼容迁移",
        sync_mode: "文件同步",
        target_reason: "保留旧函数入口，方便从老式 bash 片段向分层 shell 目录过渡。",
        conflict_hint: "函数数量多且历史差异大，建议未来按函数名拆到 PG 记录，而不是整文件登记。",
        note: "legacy xlsx 里的 function 行可以优先整理进这里再做函数级抽象。",
    },
    DotfileEntry {
        slug: "shell-rc-interactive-env",
        space_slug: "xdg-config",
        logical_key: "shell.rc.interactive_env",
        label: "rc.d/30-interactive-env.sh",
        target_path: "~/.config/shell/rc.d/30-interactive-env.sh",
        kind: "Shell Export",
        platform: "Cross-platform",
        status: "已整理",
        sync_mode: "文件同步",
        target_reason: "放只对交互 shell 生效的环境变量，避免污染 login 环境层。",
        conflict_hint: "一旦涉及 Node 或代理变量，建议在变更前做上下文提示。",
        note: "虽然内容很短，但在元数据表里应单独可见。",
    },
    DotfileEntry {
        slug: "shell-rc-local-compat",
        space_slug: "xdg-config",
        logical_key: "shell.rc.local_compat",
        label: "rc.d/90-local-compat.sh",
        target_path: "~/.config/shell/rc.d/90-local-compat.sh",
        kind: "Shell Shim",
        platform: "macOS/Linux",
        status: "兼容迁移",
        sync_mode: "文件同步",
        target_reason: "保留对旧 ~/.add_fn 的兼容开关，让本地历史片段逐步退出主干。",
        conflict_hint: "只有明确开启兼容标记时才应该生效，避免默认注入旧逻辑。",
        note: "这是兼容层元数据，不应和正式 export / alias / function 混淆。",
    },
    DotfileEntry {
        slug: "shell-zsh-oh-my-zsh",
        space_slug: "xdg-config",
        logical_key: "shell.zsh.oh_my_zsh",
        label: "zshrc.d/10-oh-my-zsh.zsh",
        target_path: "~/.config/shell/zshrc.d/10-oh-my-zsh.zsh",
        kind: "Zsh Module",
        platform: "macOS",
        status: "已整理",
        sync_mode: "文件同步",
        target_reason: "管理 Zsh 主题、plugin 和 compdump 缓存，是 Zsh 专属交互层入口。",
        conflict_hint: "主题和 plugin 列表可能随机器差异变化，建议支持数组级 diff。",
        note: "属于 zsh-only 元数据，和 bash 通用片段分开管理。",
    },
    DotfileEntry {
        slug: "shell-zsh-enhancements",
        space_slug: "xdg-config",
        logical_key: "shell.zsh.enhancements",
        label: "zshrc.d/20-enhancements.zsh",
        target_path: "~/.config/shell/zshrc.d/20-enhancements.zsh",
        kind: "Zsh Module",
        platform: "macOS",
        status: "已整理",
        sync_mode: "文件同步",
        target_reason: "负责 autosuggestions、syntax highlighting、autojump 等增强能力。",
        conflict_hint: "依赖 Homebrew 装包路径，若目标机缺少插件则应允许降级而非失败。",
        note: "适合登记为依赖型 shell 模块，而不是纯命令别名。",
    },
    DotfileEntry {
        slug: "shell-zsh-keybindings",
        space_slug: "xdg-config",
        logical_key: "shell.zsh.keybindings",
        label: "zshrc.d/30-keybindings.zsh",
        target_path: "~/.config/shell/zshrc.d/30-keybindings.zsh",
        kind: "Zsh Module",
        platform: "macOS",
        status: "已整理",
        sync_mode: "文件同步",
        target_reason: "集中维护 vi-mode、历史搜索和光标形态切换等交互绑定。",
        conflict_hint: "用户习惯差异大，推荐按 binding 组做预览，不要默认整段替换。",
        note: "这类键位元数据可以和 shell profile 元数据分表管理。",
    },
    DotfileEntry {
        slug: "shell-zsh-suffix-aliases",
        space_slug: "xdg-config",
        logical_key: "shell.zsh.suffix_aliases",
        label: "zshrc.d/40-suffix-aliases.zsh",
        target_path: "~/.config/shell/zshrc.d/40-suffix-aliases.zsh",
        kind: "Zsh Alias",
        platform: "macOS",
        status: "已整理",
        sync_mode: "文件同步",
        target_reason: "后缀 alias 只对 zsh 生效，应该和通用 alias 分开记账。",
        conflict_hint: "如果未来要跨 shell 同步，suffix alias 需要保持 zsh 专属边界。",
        note: "和 legacy xlsx 里的 aliass 列最接近，适合显式保留类型差异。",
    },
    DotfileEntry {
        slug: "shell-zsh-path-dedupe",
        space_slug: "xdg-config",
        logical_key: "shell.zsh.path_dedupe",
        label: "zshrc.d/90-path-dedupe.zsh",
        target_path: "~/.config/shell/zshrc.d/90-path-dedupe.zsh",
        kind: "Zsh Module",
        platform: "macOS",
        status: "已整理",
        sync_mode: "文件同步",
        target_reason: "专门做 zsh PATH 去重，避免 PATH 在多段 source 后越来越长。",
        conflict_hint: "如果其他路径策略发生变化，最好与 toolchain / path 片段一并审视。",
        note: "是 shell 行为修正模块，不建议混进普通 PATH export 表达。",
    },
    DotfileEntry {
        slug: "shell-bin-check-ip",
        space_slug: "xdg-config",
        logical_key: "shell.bin.check_ip",
        label: "bin/check-ip",
        target_path: "~/.config/shell/bin/check-ip",
        kind: "Shell Script",
        platform: "macOS/Linux",
        status: "可执行",
        sync_mode: "文件同步",
        target_reason: "作为 shell PATH 下的 helper script，负责公网 IP 监控与通知触发。",
        conflict_hint: "脚本依赖缓存文件和通知命令，变更前应提示运行时副作用。",
        note: "适合表格化记录脚本名、用途和平台，不在 Web 中执行脚本本体。",
    },
    DotfileEntry {
        slug: "shell-bin-fetch-remote-env",
        space_slug: "xdg-config",
        logical_key: "shell.bin.fetch_remote_env",
        label: "bin/fetch-remote-env",
        target_path: "~/.config/shell/bin/fetch-remote-env",
        kind: "Shell Script",
        platform: "macOS/Linux",
        status: "可执行",
        sync_mode: "文件同步",
        target_reason: "负责从远端仓库拉取 .env 并转成 export 输出，是环境装载辅助脚本。",
        conflict_hint: "涉及远端 token 和缓存文件，Web 只应登记元数据，不能展示敏感内容。",
        note: "对齐 xlsx 的 export 元数据思路，但保留 secret value 在本地脚本运行时解析。",
    },
    DotfileEntry {
        slug: "shell-bin-send-file",
        space_slug: "xdg-config",
        logical_key: "shell.bin.send_file",
        label: "bin/send-file",
        target_path: "~/.config/shell/bin/send-file",
        kind: "Shell Script",
        platform: "macOS/Linux",
        status: "可执行",
        sync_mode: "文件同步",
        target_reason: "提供 scp 传输包装器，属于用户 shell 工具箱的一部分。",
        conflict_hint: "涉及远端地址和端口参数，建议把默认参数与脚本实现分开登记。",
        note: "适合作为 file metadata 行管理，而不是并入 alias / function 列。",
    },
    DotfileEntry {
        slug: "shell-local-private-env",
        space_slug: "xdg-config",
        logical_key: "shell.local.private_env",
        label: "local.profile.d/10-private-env.sh",
        target_path: "~/.config/shell/local.profile.d/10-private-env.sh",
        kind: "Private Export",
        platform: "macOS",
        status: "私密本地",
        sync_mode: "仅元数据",
        target_reason: "本地私有 token、密码和 API key 需要登记目标位置与用途，但不应在 Web 中回显值。",
        conflict_hint: "禁止自动回显 secret value；只允许显示文件级元数据、变量名策略和同步边界。",
        note: "参考 biz_dotfiles.xlsx 的列结构，但这里明确只吸收 os_type / def_type / name / status / location 一类元数据。",
    },
    DotfileEntry {
        slug: "shell-local-zsh-addclaw",
        space_slug: "xdg-config",
        logical_key: "shell.local.zsh.addclaw",
        label: "local.zshrc.d/addclaw.zsh",
        target_path: "~/.config/shell/local.zshrc.d/addclaw.zsh",
        kind: "Local Extension",
        platform: "macOS",
        status: "本地扩展",
        sync_mode: "本地保留",
        target_reason: "本地 zsh 扩展函数可继续保留在 local 目录，不进入公共主干同步。",
        conflict_hint: "默认不应覆盖其他机器的 local 扩展，只在显式导入时同步。",
        note: "适合作为 local-only 元数据展示，让 shell 目录里的私有扩展也能统一进表。",
    },
    DotfileEntry {
        slug: "iterm2-plist",
        space_slug: "macos-library",
        logical_key: "desktop.iterm2_prefs",
        label: "iTerm2 plist",
        target_path: "~/Library/Preferences/com.googlecode.iterm2.plist",
        kind: "GUI Preference",
        platform: "macOS",
        status: "已登记",
        sync_mode: "能力受限",
        target_reason: "iTerm2 配置仍按 Preferences 落地，但期望态和同步决策由 PG 统一管理。",
        conflict_hint: "建议先只做登记和导出，真正自动写回前需要单独的 plist 策略。",
        note: "Web 不把 plist 强拉回 ~/.config，而是维护云端记录和目标路径。",
    },
    DotfileEntry {
        slug: "cursor-user",
        space_slug: "macos-library",
        logical_key: "editor.cursor_user",
        label: "Cursor User",
        target_path: "~/Library/Application Support/Cursor/User/",
        kind: "GUI Workspace",
        platform: "macOS",
        status: "已登记",
        sync_mode: "目录同步",
        target_reason: "Electron 应用继续按 Application Support 落地，PG 保存统一配置视图。",
        conflict_hint: "适合文件级 diff；settings、keybindings 和 snippets 可分开确认。",
        note: "settings.json、keybindings.json 和 snippets 后续可再细分。",
    },
    DotfileEntry {
        slug: "vscode-user",
        space_slug: "macos-library",
        logical_key: "editor.vscode_user",
        label: "VS Code User",
        target_path: "~/Library/Application Support/Code/User/",
        kind: "GUI Workspace",
        platform: "macOS",
        status: "已登记",
        sync_mode: "目录同步",
        target_reason: "VS Code 用户配置仍然按原生目录落地，PG 只做云端统一管理和同步编排。",
        conflict_hint: "与 Cursor 类似，先做文件级预览，再决定是否覆盖本机工作区设置。",
        note: "若未来需要跨编辑器同步，可在 PG 中维护逻辑组而不是搬迁真实文件。",
    },
    DotfileEntry {
        slug: "etc-hosts",
        space_slug: "system",
        logical_key: "system.hosts",
        label: "hosts",
        target_path: "/etc/hosts",
        kind: "Network Override",
        platform: "macOS",
        status: "已登记",
        sync_mode: "提权同步",
        target_reason: "系统级 hosts 必须保留在 /etc，PG 记录期望态，agent 在提权后选择是否 apply。",
        conflict_hint: "默认必须人工确认，尤其当本机已有临时域名映射时不能自动覆盖。",
        note: "适合后续接入审计、差异预览与提权写回。",
    },
    DotfileEntry {
        slug: "etc-ssh-config",
        space_slug: "system",
        logical_key: "system.ssh_config_d",
        label: "ssh_config.d/",
        target_path: "/etc/ssh/ssh_config.d/",
        kind: "System Policy",
        platform: "macOS/Linux",
        status: "已登记",
        sync_mode: "提权同步",
        target_reason: "系统默认 SSH 策略需要和用户级配置分层，PG 统一管理策略内容与目标路径。",
        conflict_hint: "适合目录片段级 apply，冲突时必须保守处理并要求人工确认。",
        note: "后续 agent apply 应该按目录片段增量下发，而不是整目录覆盖。",
    },
];

pub fn dotfile_space(slug: &str) -> Option<&'static DotfileSpace> {
    DOTFILE_SPACES.iter().find(|space| space.slug == slug)
}

pub fn dotfile_entry(slug: &str) -> Option<&'static DotfileEntry> {
    DOTFILE_ENTRIES.iter().find(|entry| entry.slug == slug)
}

pub fn dotfile_entries(space_slug: &str) -> impl Iterator<Item = &'static DotfileEntry> {
    DOTFILE_ENTRIES
        .iter()
        .filter(move |entry| entry.space_slug == space_slug)
}

pub fn dotfile_entry_count(space_slug: &str) -> usize {
    dotfile_entries(space_slug).count()
}

pub fn first_entry_slug_for_space(space_slug: &str) -> Option<&'static str> {
    dotfile_entries(space_slug).next().map(|entry| entry.slug)
}

pub fn total_managed_spaces() -> usize {
    DOTFILE_SPACES.len()
}

pub fn total_managed_entries() -> usize {
    DOTFILE_ENTRIES.len()
}
