[package]
name = "aio-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
az-aio-client.workspace = true
az-derive-aliases.workspace = true
az-config-center-contract.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tauri = "2.11.2"
tokio.workspace = true
uuid.workspace = true
rfd = "0.17.2"

[build-dependencies]
tauri-build = "2.6.2"

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
